name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  integration-tests:
    strategy:
      matrix:
        containerGoVer:
          - "1.20"
          - "1.21-rc"
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_DATABASE: gorptest
          MYSQL_USER: gorptest
          MYSQL_PASSWORD: gorptest
          MYSQL_RANDOM_ROOT_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Integration Tests
        run: ./test_all.sh

  quick-tests:
    strategy:
      matrix:
        containerGoVer:
          - "1.20"
          - "1.21-rc"
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Go Build
      run: go build -v ./...

    - name: Unit Tests
      run: go test -v ./...

  govulncheck:
    strategy:
      matrix:
        containerGoVer:
          - "1.20"
          - "1.21-rc"
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
