name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  integration-tests:
    strategy:
      matrix:
        containerGoVer:
          - "1.20"
          - "1.21-rc"
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_DATABASE: gorptest
          MYSQL_USER: gorptest
          MYSQL_PASSWORD: gorptest
          MYSQL_RANDOM_ROOT_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Integration Tests
        run: ./test_all.sh

  quick-tests:
    strategy:
      matrix:
        containerGoVer:
          - "1.20"
          - "1.21-rc"
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Go Build
      run: go build -v ./...

    - name: Unit Tests
      run: go test -v ./...

  gvc:
    strategy:
      matrix:
        include:
          - containerGoVer: "1.20"
            setupGoVer: "1.20.5"
          - containerGoVer: "1.21-rc"
            setupGoVer: "1.21.0-rc.2" # https://github.com/actions/setup-go#v3
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containerGoVer }}
    steps:
    - id: govulncheck
      uses: golang/govulncheck-action@v0.2.0
      with:
        go-version: ${{ matrix.setupGoVer }}
